model = "gpt-5.1-codex-max"
model_reasoning_effort = "high"
sandbox_mode = "danger-full-access"

[sandbox_workspace_write]
network_access = true
[features]
web_search_request = true

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
hide_gpt5_1_migration_prompt = true
hide_rate_limit_model_nudge = true
